Repository NCAR/wrfcloud, pull requests merged in 2022-09, with the labels that each got.

#60 First attempt and logging and OOP changes.
  python/src/setup.py
  python/src/wrfcloud/log.py
  python/src/wrfcloud/resources/env_vars.yaml
  python/src/wrfcloud/runtime/__init__.py
  python/src/wrfcloud/runtime/metgrid.py
  python/src/wrfcloud/runtime/postproc.py
  python/src/wrfcloud/runtime/real.py
  python/src/wrfcloud/runtime/run.py
  python/src/wrfcloud/runtime/tools/__init__.py
  python/src/wrfcloud/runtime/tools/get_grib_input.py
  python/src/wrfcloud/runtime/tools/make_wps_namelist.py
  python/src/wrfcloud/runtime/ungrib.py
  python/src/wrfcloud/runtime/wrf.py
  python/src/wrfcloud/system.py
Labels: component: NWP components

#66 feature-65/fix_grib_file_sort
  python/src/wrfcloud/runtime/ungrib.py
Labels: priority: high, type: bug, component: NWP components

#62 Feature 61/wrf jobs in UI
  python/src/wrfcloud/api/actions/__init__.py
  python/src/wrfcloud/api/actions/action.py
  python/src/wrfcloud/api/actions/jobs.py
  python/src/wrfcloud/api/actions/roles.yaml
  python/src/wrfcloud/api/actions/wrf.py
  python/src/wrfcloud/api/handler.py
  python/src/wrfcloud/jobs/__init__.py
  python/src/wrfcloud/jobs/job_dao.py
  python/src/wrfcloud/resources/env_vars.yaml
  python/src/wrfcloud/setup/aws/cf_wrfcloud_certificate.yaml
  python/src/wrfcloud/setup/aws/cf_wrfcloud_data.yaml
  python/src/wrfcloud/setup/aws/cf_wrfcloud_webapp.yaml
  python/src/wrfcloud/subscribers/__init__.py
  python/src/wrfcloud/subscribers/subscriber.py
  python/src/wrfcloud/subscribers/subscriber_dao.py
  python/src/wrfcloud/subscribers/table.yaml
  python/src/wrfcloud/subscribers/websocket_tools.py
  python/test/resources/sample_subscribers.yaml
  python/test/wrfcloud/helper.py
  python/test/wrfcloud/test_api_actions.py
  python/test/wrfcloud/test_api_handler.py
  python/test/wrfcloud/test_subscribers.py
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/app/client-api.ts
  web/src/app/view-jobs/view-jobs.component.html
  web/src/app/view-jobs/view-jobs.component.ts
Labels: component: API, component: web ui

#67 A number of QOL improvements in preparation for real and WRF tasks
  python/src/wrfcloud/runtime/__init__.py
  python/src/wrfcloud/runtime/metgrid.py
  python/src/wrfcloud/runtime/run.py
  python/src/wrfcloud/runtime/test.yml
  python/src/wrfcloud/runtime/tools/check_wd_exist.py
  python/src/wrfcloud/runtime/tools/make_wps_namelist.py
  python/src/wrfcloud/runtime/ungrib.py
Labels: priority: blocker, priority: high, type: enhancement, component: NWP components

#69 Add real.exe and WRF capabilities
  python/src/wrfcloud/runtime/__init__.py
  python/src/wrfcloud/runtime/configurations/test/namelist.input
  python/src/wrfcloud/runtime/metgrid.py
  python/src/wrfcloud/runtime/real.py
  python/src/wrfcloud/runtime/tools/__init__.py
  python/src/wrfcloud/runtime/tools/check_wd_exist.py
  python/src/wrfcloud/runtime/tools/make_wps_namelist.py
  python/src/wrfcloud/runtime/tools/make_wrf_namelist.py
  python/src/wrfcloud/runtime/wrf.py
Labels: priority: high, type: enhancement, component: NWP components

#72 Changed the compute nodes to a type with EFA.
  python/src/wrfcloud/aws/pcluster.py
  python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml
  python/src/wrfcloud/aws/resources/cluster.wrfcloud.yaml
Labels: component: AWS Cluster, component: NWP components

#75 Add logic for parallel job submission through slurm
  python/src/wrfcloud/runtime/__init__.py
  python/src/wrfcloud/runtime/real.py
  python/src/wrfcloud/runtime/test.yml
  python/src/wrfcloud/runtime/tools/make_wrf_namelist.py
  python/src/wrfcloud/runtime/wrf.py
Labels: priority: high, type: new feature, component: NWP components
