Repository NCAR/wrfcloud, pull requests merged in 2022-08, with the labels that each got.

#27 Feature/wrf to geojson
  python/src/.pylintrc
  python/src/setup.py
  python/src/wrfcloud/runtime/tools/__init__.py
  python/src/wrfcloud/runtime/tools/geojson.py
Labels: type: new feature, component: graphics

#25 feature 22/nwp_scripts
  python/src/wrfcloud/runtime/__init__.py
  python/src/wrfcloud/runtime/metgrid.py
  python/src/wrfcloud/runtime/ungrib.py
Labels: priority: high, type: new feature, component: NWP components

#45 Feature/openlayer map
  web/angular.json
  web/package.json
  web/src/app/activate/activate.component.ts
  web/src/app/app-routing.module.ts
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/app/client-api.ts
  web/src/app/edit-user/edit-user.component.ts
  web/src/app/layer/layer.component.html
  web/src/app/layer/layer.component.sass
  web/src/app/layer/layer.component.spec.ts
  web/src/app/layer/layer.component.ts
  web/src/app/login/login.component.ts
  web/src/app/manage-users/manage-users.component.ts
  web/src/app/preferences/preferences.component.ts
  web/src/app/reset-password/reset-password.component.ts
  web/src/app/view-jobs/view-jobs.component.html
  web/src/app/view-jobs/view-jobs.component.ts
  web/src/app/wrf-viewer/wrf-viewer.component.html
  web/src/app/wrf-viewer/wrf-viewer.component.sass
  web/src/app/wrf-viewer/wrf-viewer.component.spec.ts
  web/src/app/wrf-viewer/wrf-viewer.component.ts
  web/src/assets/pause.png
  web/src/assets/play.png
  web/src/assets/step_back.png
  web/src/assets/step_forward.png
  web/src/palette.sass
  web/src/styles.sass
  web/tsconfig.json
Labels: component: web ui

#30 Feature 28/pull gfs data
  python/src/setup.py
  python/src/wrfcloud/resources/env_vars.yaml
  python/src/wrfcloud/runtime/__init__.py
  python/src/wrfcloud/runtime/run.py
  python/src/wrfcloud/runtime/tools/__init__.py
  python/src/wrfcloud/runtime/tools/get_grib_input.py
  python/src/wrfcloud/runtime/ungrib.py
Labels: priority: high, type: enhancement, component: NWP components

#52 Feature 50/ Install UPP
  python/src/wrfcloud/aws/pcluster.py
  python/src/wrfcloud/aws/resources/cf_imagebuilder_wrf_intel.yaml
Labels: priority: medium, type: new feature, component: AWS Cluster, component: NWP components

#33 Address issue #23
  python/src/wrfcloud/runtime/__init__.py
  python/src/wrfcloud/runtime/configurations/test/namelist.wps
  python/src/wrfcloud/runtime/metgrid.py
  python/src/wrfcloud/runtime/run.py
  python/src/wrfcloud/runtime/test.yml
  python/src/wrfcloud/runtime/ungrib.py
Labels: priority: medium, component: NWP components

#59 WRF Job data model and CRUD operations.
  python/src/wrfcloud/jobs/__init__.py
  python/src/wrfcloud/jobs/job.py
  python/src/wrfcloud/jobs/job_dao.py
  python/src/wrfcloud/jobs/table.yaml
  python/src/wrfcloud/resources/env_vars.yaml
  python/src/wrfcloud/setup/aws/cf_wrfcloud_data.yaml
  python/test/resources/sample_jobs.yaml
  python/test/wrfcloud/helper.py
  python/test/wrfcloud/test_jobs.py
Labels: priority: blocker, component: API
