Repository NCAR/wrfcloud, pull requests merged in 2023-02, with the labels that each got.

#137 Feature/116 Add a license
  LICENSE.md
Labels: priority: high, required: FOR OFFICIAL RELEASE, type: task

#149 Feature/139 job details and delete
  python/src/wrfcloud/api/actions/__init__.py
  python/src/wrfcloud/api/actions/jobs.py
  python/src/wrfcloud/api/actions/roles.yaml
  python/src/wrfcloud/aws/pcluster.py
  python/src/wrfcloud/jobs/__init__.py
  python/src/wrfcloud/jobs/job_dao.py
  web/src/app/app.module.ts
  web/src/app/client-api.ts
  web/src/app/job-details/job-details.component.html
  web/src/app/job-details/job-details.component.sass
  web/src/app/job-details/job-details.component.spec.ts
  web/src/app/job-details/job-details.component.ts
  web/src/app/login/login.component.html
  web/src/app/login/login.component.ts
  web/src/app/view-jobs/view-jobs.component.html
  web/src/app/view-jobs/view-jobs.component.sass
  web/src/app/view-jobs/view-jobs.component.ts
Labels: component: API, component: web ui

#152 Bug/151 mime type
  .gitignore
  docs/Users_Guide/installation.rst
  python/src/wrfcloud/setup/__init__.py
Labels: component: release and repository
